### ISSUE TITLE
Pets in Code window

### ISSUE THREAD

**Issue by CITIZENDOT** [tonybaloney/vscode-pets#76] opened 2021-12-09 05:23 UTC
It would be cool if pets are in the actual code window rather than a separate panel.
Or a toggle switch between the panel and active editor is also better.

**Comment by lem0n4id** [comment] 2021-12-09 10:46
Hey, you can move the panel to Explorer pane if you want. (It's not the code window tho)

![image](https://user-images.githubusercontent.com/61219881/145382042-f48e1149-02c9-4cc3-986e-e13da3363713.png)

You can do this by changing the position to explorer in settings
![image](https://user-images.githubusercontent.com/61219881/145382262-e9eab5a1-bff0-4e7b-97d4-9a25e77b4551.png)

**Comment by tonybaloney** [comment] 2021-12-14 21:04
Duplicate of #73 (the short answer is this isn't possible)

**Closed by tonybaloney** 2021-12-14 21:04 UTC
