### ISSUE TITLE
Inline pet into code editor window

### ISSUE THREAD

**Issue by gm112** [tonybaloney/vscode-pets#95] opened 2022-02-14 19:28 UTC
Having the extra panel seems like a sub-optimal use of screen estate. Is it possible within VSCode to have the pets run around behind the code?

**Comment by tonybaloney** [comment] 2022-02-14 20:43
Duplicate of #4 

The answer sadly is no, this isn't possible.

**Closed by tonybaloney** 2022-02-14 20:43 UTC
