### ISSUE TITLE
Overlay pets on files.

### ISSUE THREAD

**Issue by cscott20** [tonybaloney/vscode-pets#71] opened 2021-12-05 10:59 UTC
I would love if this extension could overlay pets on whichever file is currently open!

**Comment by tonybaloney** [comment] 2021-12-07 08:04
duplicate of https://github.com/tonybaloney/vscode-pets/issues/4

The answer sadly is no,

**Closed by tonybaloney** 2021-12-07 08:04 UTC

**Comment by cscott20** [comment] 2021-12-07 08:21
Any reason? Is it not easy / possible to implement?

**Comment by tonybaloney** [comment] 2021-12-07 10:47
It's not possible. VS code doesn't provide an API for anything like that. We're constrained to the panel
