### ISSUE TITLE
Not working in code server

### ISSUE THREAD

**Issue by UntrustedTech** [tonybaloney/vscode-pets#281] opened 2022-10-19 17:34 UTC
So ive been working on local hosted code server for a while and i thought this would be a cute little thing to have on my code setup, ive tried to get it to work but even reloading it or adding pets doesn’t work.

**Comment by tonybaloney** [comment] 2022-10-19 22:29
Duplicate of #256 am working on fix

**Closed by tonybaloney** 2022-10-19 22:29 UTC
