### ISSUE TITLE
Idea for the pets to make them less bulky

### ISSUE THREAD

**Issue by DJREMiX6** [tonybaloney/vscode-pets#83] opened 2021-12-14 01:15 UTC
I think, if it's possible, that the pets will be more fun and less bulky if we can have them in the bottom border of the code window, without setting the background and interacting with them with the mouse's cursor so you don't have to have another useless opened window and you can focus more to the code

**Comment by tonybaloney** [comment] 2021-12-14 21:04
Duplicate of #73 (the short answer is this isn't possible)

**Closed by tonybaloney** 2021-12-14 21:04 UTC
